config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'questions#index'

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :comments, shallow: true, only: [:create, :destroy], defaults: { commentable: 'questions' }
    resources :answers, shallow: true, concerns: :votable  do
      member do
        post 'best'
      end
      resources :comments, only: [:create, :destroy], defaults: { commentable: 'answers' }
    end
  end
  resources :attachments, only: :destroy

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Commentable
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable
  validates :content, :question_id, :user_id, presence: true
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
  default_scope { order(best: :desc) }
  def make_best
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  belongs_to :attachable, polymorphic: true

  mount_uploader :file, FileUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, :user_id, presence: true
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, dependent: :destroy, as: :votable
  end
  def rating
   votes.sum(:value)
  end
  def vote(user, value)
    votes.create(user: user, value: value)
  end

  def vote_reset(user)
    votes.where(user: user, votable: self).destroy
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Commentable
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable
  belongs_to :user

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
  validates :title, :body, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :votes

  def author_of?(item)
    item.user_id == self.id
  end
  def voted?(post)
    votes.where(user: self, votable: post).exists?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :user_id, presence: true, uniqueness: { scope: [:votable_type, :votable_id] }
  validates :value, inclusion: { in: [1, -1] }
  scope :votes_down,  -> { where(value: -1) }
  scope :rating,      -> { sum(:value) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: [:create, :update]
  before_action :load_answer, only:[:update, :destroy, :best]
  include Voted
  respond_to :js

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge!(user_id: current_user.id)))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    @question = @answer.question
    respond_with(@answer.destroy)
  end

  def best
    @question = @answer.question
    if current_user.author_of?(@question) && !@answer.best?
      @answer.make_best
      flash[:notice] = "This answer choose as best!"
    end
  end

private
  def load_answer
    @answer = Answer.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
  def answer_params
    params.require(:answer).permit(:content, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attachment, only: :destroy
  def destroy
    if current_user.author_of?(@attachment.attachable)
      @attachment.destroy
    else
      head(:forbidden)
    end
  end

  private
  def set_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_commentable, only: :create
  before_action :load_comment, only: :destroy
  respond_to :js
  def create
    respond_with(@comment = @commentable.comments.create(comment_params.merge!(user_id: current_user.id)))
  end

  def destroy
    respond_with(@comment.destroy)
  end
  private

  def load_commentable
    @commentable = Question.find(params[:question_id]) if params[:question_id]
    @commentable = Answer.find(params[:answer_id]) if params[:answer_id]
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def load_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/concerns/voted.rb
module Voted
  extend ActiveSupport::Concern

  included do
    before_action :set_vote, only: [:vote_up, :vote_down, :vote_reset]
  end

  def vote_up
    @votable.vote(current_user, 1) unless current_user.author_of?(@votable)
    render json: { post_id: @votable.id, rating: @votable.votes.rating, voted: true }
  end

  def vote_down
    @votable.vote(current_user, -1) unless current_user.author_of?(@votable)
    render json: { post_id: @votable.id, rating: @votable.votes.rating, voted: true }
  end

  def vote_reset
    @votable.vote_reset(current_user) unless current_user.author_of?(@votable)
    render json: { post_id: @votable.id, rating: @votable.votes.rating, voted: false }
  end

  private

  def model_class
    controller_name.classify.constantize
  end

  def set_vote
    @votable = model_class.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:update, :show, :destroy]
  before_action :load_answer, only: :show
  before_action :publish_questiom, only: :create
  include Voted
  respond_to :html, :json, :js

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end 

  def new
    respond_with(@question  = Question.new)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private

  def load_answer
    @answer = @question.answers.build
  end

  def load_question
    @question = Question.find(params[:id])
  end
  def publish_questiom
    PrivatePub.publish_to('/questions', question: @question.to_json)
  end
  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer id="answer-#{answer.id}"
    p = answer.content
    .answer-vote-area
      = render 'votes/vote_answer', post: answer

    b Attachments:
    ul
      - answer.attachments.each do |f|
        li id="attachment-#{f.id}" class="attachment"
          p= link_to f.file.identifier, f.file.url
          - if current_user && current_user.author_of?(answer)
            p= link_to "Delete file", f, method: :delete, remote: true
      end
    - if current_user && current_user.author_of?(answer)
      p= link_to 'Delete', answer_path(answer), method: :delete, remote: true
      p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
    - if current_user && current_user.author_of?(answer.question) && !answer.best?
      p= link_to 'Make best', best_answer_path(answer), method: :post, class: 'make-best-answer-link', remote: true
    - if answer.best?
      p= "Best answer!"

    - if current_user && current_user.author_of?(answer)
      p= form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
        = f.label :content, 'Answer'
        p= f.text_area :content
        p= f.submit 'Save'

    = render 'comments/comments', commentable: answer, comment: @comment
= subscribe_to "/answers/#{answer.id}/comments"

app/views/answers/best.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answers-errors').before('<%= j message %>')
  <% end %>
<% else %>
  $('.answers').html('<%= j render @question.answers %>')
  $('#answer-<%= @answer.id %>').addClass('best-answer');
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
   $('.answers-errors').before('<%= j message %>')
  <% end %>
<% else %>
  <% publish_to "/questions/#{@question.id}/answers" do %>
    $('.answers').append('<%= j render @answer %>')
  <% end %>
  $('.new_answer #answer_content').val('')
<% end %>

app/views/answers/destroy.js.erb
$("<%= "#answer-#{@answer.id}" %>").remove();

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answers-errors').before('<%= j message %>')
  <% end %>
<% else %>
  $('#answer-<%= @answer.id %>').replaceWith('<%= j render @answer %>');

  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });
<% end %>

app/views/attachments/_attachment_fields.html.slim
.nested-fields
  .field
    p= f.label :file
    p
      = f.file_field :file
      = link_to_remove_association 'Remove file', f

app/views/attachments/destroy.js.erb
$('#attachment-<%= @attachment.id %>').remove();

app/views/comments/_comment.html.slim
.comment id= "comment-#{comment.id}"
p = comment.body
- if current_user && current_user.author_of?(comment)
  = link_to "Delete comment", comment_path(comment), method: :delete, remote: true

app/views/comments/_comments.html.slim
.comments
  p= "Comments"
  - commentable.comments.each do |comment|
    - if comment.persisted?
      = render comment
  - if user_signed_in?
    p= link_to 'Add a comment', '', class: 'new-comment-link', data: { commentable_id: commentable.id, commentowner: "#{commentable.class.name.underscore}-#{commentable.id}"  }
    .new-comment
      = form_for [commentable, commentable.comments.new], html: { class: 'new-comment-form' }, remote: true do |f|
        .question-comment-errors
        = f.label :body, 'Body'
        = f.text_area :body
        = f.submit 'Post comment'

app/views/comments/create.js.erb
<% if @comment.errors.present? %>
  <% @comment.errors.full_messages.each do |message| %>
    $('.errors').append('<%= j message %>');
  <% end %>
<% else %>
<% ownerId = "##{@comment.commentable_type.underscore}-#{@comment.commentable.id}" %>
  <% publish_to "/#{@comment.commentable_type.pluralize.underscore}/#{@comment.commentable.id}/comments" do %>
    $('<%= ownerId%> .comments').append("<%= j render @comment %>");
  <% end %>

  $('<%= ownerId%> .new-comment-form').val('');
  $('<%= ownerId%> .new-comment-form').hide();
  $('<%= ownerId%> .new-comment-link').show();

<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Stackoverflow
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "QnA", root_path
          .container.nav-collapse
            ul.nav
            - if user_signed_in?
              li = link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              li = link_to 'Login', new_user_session_path
              li = link_to 'Registration', new_user_registration_path
    p class='notice'= notice
    p class='alert' = alert

    = yield

app/views/questions/_answers.html.slim
  - @question.answers.each do |answer| 
    h3 
      = answer.content
      - if current_user && current_user.author_of?(answer)
        = link_to('Delete answer', [@question, answer], method: :delete) 
      br

app/views/questions/_form.html.slim
b Title:
p= question.title
.question-vote-area
  = render 'votes/vote_question', post: @question
b Body:
p= question.body
b Attachments:
ul
  -question.attachments.each do |f|
    li id="attachment-#{f.id}" class="attachment"
      p= link_to f.file.identifier, f.file.url
      - if current_user && current_user.author_of?(question)
        p= link_to "Delete file",  attachment_path(f), method: :delete, remote: true
  end
- if current_user && current_user.author_of?(question)
  p= link_to 'Delete question', question, method: :delete
  p= link_to 'Edit','', class: 'edit-question-link'

.comments-question
  = render 'comments/comments', commentable: @question, comment: @comment
= form_for question, remote: true, html: { id: "edit-question"} do |f|
  p= f.label :title, 'Title'
  p = f.text_field :title
  .question-errors
  p= f.label :body, 'Text'
  p= f.text_area :body
  p= f.submit 'Save'

app/views/questions/_question.html.slim
h3= link_to question.title, question

app/views/questions/index.html.slim
p = link_to 'Ask question', new_question_path
.questions
  p = 'Questions'
  = render @questions

  = subscribe_to "/questions"

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body, 'Text'
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = render 'attachments/attachment_fields', f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
  = f.submit 'Create'

app/views/questions/show.html.slim
.errors
p
  .question id="question-#{@question.id}"
    = render 'form', question: @question
h2 Answers:
.answers
  = render @question.answers

- if user_signed_in?
  h2 Post your Answer:
  = form_for [@question, @answer], remote: true do |f|
    = f.label :content
    .answers-errors
    = f.text_area :content
    p Attachments:
    = f.fields_for :attachments,  @answer.attachments.build do |a|
      = render 'attachments/attachment_fields', f: a
      .links
      = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
    p= f.submit 'Create answer'

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $(".question-errors").before('<%= j message %>')
  <% end %>
<% else %>
  $('.question').replaceWith("<%= j render 'form', question: @question %>");
  $('.edit-question-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    $('form#edit-question').show()
  });
<% end %>

app/views/votes/_vote_answer.html.slim
p = "Vote"
- if user_signed_in?
  - if current_user.author_of?(post)
      p = post.votes.rating
  - else
    - if current_user.voted?(post)
      p= link_to 'Vote up', vote_up_answer_path(post), class: 'vote-up hide',  method: :patch, data: { format: :json }, remote: true
      p= link_to 'Vote down', vote_down_answer_path(post), class: 'vote-down hide', method: :patch, data: { format: :json }, remote: true
      p= link_to 'Vote delete', vote_reset_answer_path(post), class: 'vote-delete', method: :delete, data: { format: :json }, remote: true
      .rating
        p = post.votes.rating
    -else
      p= link_to 'Vote up', vote_up_answer_path(post), class: 'vote-up', method: :patch, data: {format: :json}, remote: true
      p= link_to 'Vote down', vote_down_answer_path(post), class: 'vote-down', method: :patch, data: {format: :json}, remote: true
      p= link_to 'Vote delete', vote_reset_answer_path(post), class: 'vote-delete hide', method: :delete, data: {format: :json}, remote: true
      .rating
        p = post.votes.rating

- else
  .rating
    p = post.votes.rating

app/views/votes/_vote_question.html.slim
p = "Vote"
- if user_signed_in?
  - if current_user.author_of?(post)
      p = post.votes.rating
  - else
    - if current_user.voted?(post)
      p= link_to 'Vote up', vote_up_question_path(post), class: 'vote-up hide',  method: :patch, data: { format: :json }, remote: true
      p= link_to 'Vote down', vote_down_question_path(post), class: 'vote-down hide', method: :patch, data: { format: :json }, remote: true
      p= link_to 'Vote delete', vote_reset_question_path(post), class: 'vote-delete', method: :delete, data: { format: :json }, remote: true
      .rating
        p = post.votes.rating
    -else
      p= link_to 'Vote up', vote_up_question_path(post), class: 'vote-up', method: :patch, data: {format: :json}, remote: true
      p= link_to 'Vote down', vote_down_question_path(post), class: 'vote-down', method: :patch, data: {format: :json}, remote: true
      p= link_to 'Vote delete', vote_reset_question_path(post), class: 'vote-delete hide', method: :delete, data: {format: :json}, remote: true
      .rating
        p = post.votes.rating

- else
  .rating
    p = post.votes.rating